GenreList.create(name: "お茶")
GenreList.create(name: "紅茶")
GenreList.create(name: "コーヒー")
GenreList.create(name: "スポーツドリンク")
GenreList.create(name: "水")
GenreList.create(name: "果実・野菜ジュース")
GenreList.create(name: "炭酸ジュース")
GenreList.create(name: "その他")
