GenreList.create(name: "お茶")
GenreList.create(name: "紅茶")
GenreList.create(name: "コーヒー")
GenreList.create(name: "スポーツドリンク")
GenreList.create(name: "水")
GenreList.create(name: "果実・野菜ジュース")
GenreList.create(name: "炭酸ジュース")
GenreList.create(name: "その他")

Vending.create(lat: 35.700889, lon: 139.771905, func: "ゴミ箱")
Vending.create(lat: 35.700875, lon: 139.772114, func: "ゴミ箱,IC")
Vending.create(lat: 35.700834, lon: 139.772128, func: "ゴミ箱,IC")
Vending.create(lat: 35.700817, lon: 139.772122, func: "ゴミ箱,IC")
Vending.create(lat: 35.700794, lon: 139.772115, func: "ゴミ箱,IC")
Vending.create(lat: 35.700805, lon: 139.772118, func: "ゴミ箱,IC")
Vending.create(lat: 35.700800, lon: 139.772117, func: "ゴミ箱,IC")
Vending.create(lat: 35.701021, lon: 139.771918, func: "ゴミ箱")
Vending.create(lat: 35.701021, lon: 139.771918, func: "ゴミ箱")
Vending.create(lat: 35.699712, lon: 139.771961, func: "ゴミ箱,IC")
Vending.create(lat: 35.699712, lon: 139.771961, func: "ゴミ箱,IC")
Vending.create(lat: 35.699712, lon: 139.771961, func: "ゴミ箱,IC")
Vending.create(lat: 35.700285, lon: 139.771870, func: "")
Vending.create(lat: 35.701101, lon: 139.771723, func: "")
Vending.create(lat: 35.701407, lon: 139.771842, func: "ゴミ箱")
Vending.create(lat: 35.701407, lon: 139.771842, func: "ゴミ箱")
Vending.create(lat: 35.701407, lon: 139.771842, func: "ゴミ箱")
Vending.create(lat: 35.701407, lon: 139.771842, func: "ゴミ箱")
Vending.create(lat: 35.701426, lon: 139.772116, func: "ゴミ箱")
Vending.create(lat: 35.701426, lon: 139.772116, func: "ゴミ箱")
Vending.create(lat: 35.701849, lon: 139.772583, func: "IC")

Drink.create(genre_id: 1, name: "やさしい麦茶")
Drink.create(genre_id: 1, name: "爽健美茶")
Drink.create(genre_id: 1, name: "からだすこやか茶W")
Drink.create(genre_id: 1, name: "からだ巡茶")
Drink.create(genre_id: 1, name: "香ばし麦茶")
Drink.create(genre_id: 1, name: "にっぽん烏龍")
Drink.create(genre_id: 1, name: "伊右衛門茶")
Drink.create(genre_id: 1, name: "伊右衛門焙じ茶")
Drink.create(genre_id: 1, name: "伊右衛門特茶")
Drink.create(genre_id: 1, name: "伊右衛門特茶カフェインゼロ")
Drink.create(genre_id: 1, name: "綾鷹")
Drink.create(genre_id: 1, name: "綾鷹上煎茶")
Drink.create(genre_id: 1, name: "綾鷹抹茶ラテ")
Drink.create(genre_id: 1, name: "生茶")
Drink.create(genre_id: 1, name: "玉露入りお茶")
Drink.create(genre_id: 1, name: "旨みの日本茶")
Drink.create(genre_id: 1, name: "十六茶")
Drink.create(genre_id: 2, name: "アイスティー微糖")
Drink.create(genre_id: 2, name: "リプトンアップルティー")
Drink.create(genre_id: 2, name: "リプトン白の贅沢ミルクティー")
Drink.create(genre_id: 2, name: "午後の紅茶おいしい無糖")
Drink.create(genre_id: 2, name: "午後の紅茶エスプレッソティーラテ")
Drink.create(genre_id: 2, name: "午後の紅茶プレミアムストレート")
Drink.create(genre_id: 2, name: "午後の紅茶ミルクティー")
Drink.create(genre_id: 2, name: "午後の紅茶あたたかいミルクティー")
Drink.create(genre_id: 2, name: "午後の紅茶芳醇ロイヤルミルクティー")
Drink.create(genre_id: 2, name: "紅茶花伝ロイヤルミルクティー")
Drink.create(genre_id: 2, name: "紅茶花伝ロイヤルストレートティー")
Drink.create(genre_id: 2, name: "ロイヤルミルクティー")
Drink.create(genre_id: 2, name: "あったかいミルクティー")
Drink.create(genre_id: 3, name: "ボスプレミアム")
Drink.create(genre_id: 3, name: "プレミアムボス リミテッド")
Drink.create(genre_id: 3, name: "ボスプレミアムブラック")
Drink.create(genre_id: 3, name: "ボスレインボー")
Drink.create(genre_id: 3, name: "ボスブラック")
Drink.create(genre_id: 3, name: "ボスファイブスター")
Drink.create(genre_id: 3, name: "ボスカフェオレ")
Drink.create(genre_id: 3, name: "ボスマスターズコーヒー")
Drink.create(genre_id: 3, name: "ボス贅沢微糖")
Drink.create(genre_id: 3, name: "ジョージアザプレミアム")
Drink.create(genre_id: 3, name: "ジョージアヨーロピアン香るブラック")
Drink.create(genre_id: 3, name: "ジョージアヨーロピアン熟練ブレンド")
Drink.create(genre_id: 3, name: "ジョージアエスプレッソブレンドギフト")
Drink.create(genre_id: 3, name: "ジョージア贅沢カフェラテ")
Drink.create(genre_id: 3, name: "ジョージアプレミアムカフェラテ")
Drink.create(genre_id: 3, name: "ジョージア贅沢生クリームのカフェオレ")
Drink.create(genre_id: 3, name: "ジョージアエメラルドマウンテンブレンド至福の微糖")
Drink.create(genre_id: 3, name: "ジョージアエメラルドマウンテンブレンドブラック")
Drink.create(genre_id: 3, name: "ジョージアエメラルドマウンテンブレンド")
Drink.create(genre_id: 3, name: "ファイア")
Drink.create(genre_id: 3, name: "ファイアエクストリームブレンド")
Drink.create(genre_id: 3, name: "ファイア挽きたて微糖")
Drink.create(genre_id: 3, name: "ファイア香ばしブラック")
Drink.create(genre_id: 3, name: "ファイアブラック")
Drink.create(genre_id: 3, name: "ファイア冷や水重ね焼き")
Drink.create(genre_id: 3, name: "ファイアディープブレンド")
Drink.create(genre_id: 3, name: "ファイアエクストリームブレンド")
Drink.create(genre_id: 3, name: "ファイアカフェラテ")
Drink.create(genre_id: 3, name: "ドトールカフェオレ")
Drink.create(genre_id: 3, name: "限定焙煎")
Drink.create(genre_id: 3, name: "世界一バリスタ")
Drink.create(genre_id: 3, name: "ダイドーブレンド")
Drink.create(genre_id: 3, name: "ワンダ")
Drink.create(genre_id: 3, name: "ワンダ青空の一服微糖")
Drink.create(genre_id: 3, name: "ワンダエクストラショット")
Drink.create(genre_id: 3, name: "ワンダ特性カフェオレ")
Drink.create(genre_id: 3, name: "ワンダ極ブラック")
Drink.create(genre_id: 3, name: "ワンダ炭火の季節")
Drink.create(genre_id: 3, name: "ワンダ金の微糖")
Drink.create(genre_id: 3, name: "ワンダモーニングショット")
Drink.create(genre_id: 3, name: "UCCビーンズロースターズカフェラテ")
Drink.create(genre_id: 3, name: "UCCブラック無糖")
Drink.create(genre_id: 3, name: "冴えるブラック")
Drink.create(genre_id: 3, name: "上島珈琲店ミルク珈琲")
Drink.create(genre_id: 3, name: "アロマックスクオリティブラック")
Drink.create(genre_id: 3, name: "アロマックスキャラメルマキアート")
Drink.create(genre_id: 3, name: "アロマックスプレミアムゴールド")
Drink.create(genre_id: 3, name: "ジョージアマックスコーヒー")
Drink.create(genre_id: 3, name: "ポッカコーヒー")
Drink.create(genre_id: 3, name: "ポッカコーヒー厳選微糖")
Drink.create(genre_id: 3, name: "ポッカサッポロくつろぎカフェオレ")
Drink.create(genre_id: 3, name: "ポッカサッポロ深煎りブラック")
Drink.create(genre_id: 3, name: "ミルクカフェ")
Drink.create(genre_id: 4, name: "アミノサプリC")
Drink.create(genre_id: 4, name: "グリーンダカラ")
Drink.create(genre_id: 4, name: "ポカリスエット")
Drink.create(genre_id: 4, name: "アクエリアス")
Drink.create(genre_id: 4, name: "アクエリアスビタミン")
Drink.create(genre_id: 4, name: "スポーツウォーター")
Drink.create(genre_id: 4, name: "キリンラブズスポーツ")
Drink.create(genre_id: 5, name: "ボルビック")
Drink.create(genre_id: 5, name: "南アルプス天然水オレンジ")
Drink.create(genre_id: 5, name: "贅沢ヨーグリーナ")
Drink.create(genre_id: 5, name: "天然水グレープ")
Drink.create(genre_id: 5, name: "バナジウム天然水")
Drink.create(genre_id: 5, name: "スーパーH2O")
Drink.create(genre_id: 5, name: "富士山麓のおいしい天然水")
Drink.create(genre_id: 5, name: "白桃香るおいしい水")
Drink.create(genre_id: 5, name: "いろはす天然水")
Drink.create(genre_id: 5, name: "いろはす温州みかん")
Drink.create(genre_id: 5, name: "いろはすもも")
Drink.create(genre_id: 6, name: "トロピカーナ")
Drink.create(genre_id: 6, name: "純水りんご")
Drink.create(genre_id: 6, name: "ウェルチグレープ")
Drink.create(genre_id: 6, name: "ウェルチフルーツウォーターレモン")
Drink.create(genre_id: 6, name: "アセロラリフレッシュ")
Drink.create(genre_id: 6, name: "なっちゃんオレンジ")
Drink.create(genre_id: 6, name: "なっちゃんりんご")
Drink.create(genre_id: 6, name: "ネクターピーチ")
Drink.create(genre_id: 6, name: "ミニッツメイドオレンジブレンド")
Drink.create(genre_id: 6, name: "ミニッツメイドピンクグレープフルーツブレンド")
Drink.create(genre_id: 6, name: "バヤリースさらさら毎日おいしくトマト")
Drink.create(genre_id: 7, name: "コカコーラ")
Drink.create(genre_id: 7, name: "コカコーラゼロ")
Drink.create(genre_id: 7, name: "ペプシコーラ")
Drink.create(genre_id: 7, name: "ペプシストロング")
Drink.create(genre_id: 7, name: "ペプシリフレッシュショット")
Drink.create(genre_id: 7, name: "オランジーナ")
Drink.create(genre_id: 7, name: "オランジーナ贅沢ビターオレンジ")
Drink.create(genre_id: 7, name: "デカビタ")
Drink.create(genre_id: 7, name: "レモンスカッシュ")
Drink.create(genre_id: 7, name: "メッツレモンスカッシュ")
Drink.create(genre_id: 7, name: "力水")
Drink.create(genre_id: 7, name: "レッドブル")
Drink.create(genre_id: 7, name: "レッドブルシュガーフリー")
Drink.create(genre_id: 7, name: "ドデカミンストロング")
Drink.create(genre_id: 7, name: "ポップメロンソーダ")
Drink.create(genre_id: 7, name: "C.C.レモン")
Drink.create(genre_id: 7, name: "ファンタレモン+C")
Drink.create(genre_id: 7, name: "ファンタレモンアップル")
Drink.create(genre_id: 7, name: "ファンタレモンピーチ")
Drink.create(genre_id: 7, name: "ファンタレモングレープ")
Drink.create(genre_id: 7, name: "スコール")
Drink.create(genre_id: 7, name: "スプライト")
Drink.create(genre_id: 7, name: "C1000ちょっと濃い目の優しいレモン")
Drink.create(genre_id: 7, name: "ザレモネード")
Drink.create(genre_id: 7, name: "ビタミン炭酸マッチ")
Drink.create(genre_id: 7, name: "マウンテンデュー")
Drink.create(genre_id: 7, name: "モンスターエナジー")
Drink.create(genre_id: 7, name: "モンスターエナジーM3")
Drink.create(genre_id: 7, name: "リアルゴールド")
Drink.create(genre_id: 7, name: "リアルゴールドレモン")
Drink.create(genre_id: 7, name: "ドクターペッパー")
Drink.create(genre_id: 7, name: "カナダドライクラブソーダ")
Drink.create(genre_id: 7, name: "ウィルキンソン炭酸水")
Drink.create(genre_id: 7, name: "天然水スパークリング")
Drink.create(genre_id: 7, name: "いろはすサイダー")
Drink.create(genre_id: 7, name: "三ツ矢サイダー")
Drink.create(genre_id: 7, name: "カルピスソーダ")
Drink.create(genre_id: 8, name: "ホットレモン")
Drink.create(genre_id: 8, name: "ホットレモネード")
Drink.create(genre_id: 8, name: "ぽっかぽかレモン")
Drink.create(genre_id: 8, name: "おしるこ")
Drink.create(genre_id: 8, name: "つぶ入りおしるこ")
Drink.create(genre_id: 8, name: "カルピスウォーター")
Drink.create(genre_id: 8, name: "オロナミンC")
Drink.create(genre_id: 8, name: "リポビタンD")
Drink.create(genre_id: 8, name: "キレートレモンスパークショット")
Drink.create(genre_id: 8, name: "キレートレモン")
Drink.create(genre_id: 8, name: "食べるコーンポタージュ")
Drink.create(genre_id: 8, name: "つぶたっぷりコーンポタージュ")
Drink.create(genre_id: 8, name: "濃厚コーンポタージュ")
Drink.create(genre_id: 8, name: "じっくりコトコトシャキシャキつぶ入りとろーりコーン")
Drink.create(genre_id: 8, name: "じっくりコトコト濃厚オニオンコンソメ")
Drink.create(genre_id: 8, name: "じっくりコトコト海老のビスク")
Drink.create(genre_id: 8, name: "ぐんぐんグルト")
Drink.create(genre_id: 8, name: "バンホーテンミルクココア")
Drink.create(genre_id: 8, name: "香りとコクのミルクココア")
Drink.create(genre_id: 8, name: "ミルクとココア")
Drink.create(genre_id: 8, name: "いちごミルク")


VeRelationShip.create(vending_id: 1, drink_id: 115, temp: -1, value: 100);
VeRelationShip.create(vending_id: 1, drink_id: 1, temp: -1, value: 100);
VeRelationShip.create(vending_id: 1, drink_id: 9, temp: -1, value: 160);
VeRelationShip.create(vending_id: 1, drink_id: 118, temp: -1, value: 100);
VeRelationShip.create(vending_id: 1, drink_id: 120, temp: -1, value: 100);
VeRelationShip.create(vending_id: 1, drink_id: 31, temp: -1, value: 100);
VeRelationShip.create(vending_id: 1, drink_id: 34, temp: -1, value: 100);
VeRelationShip.create(vending_id: 1, drink_id: 35, temp: -1, value: 100);
VeRelationShip.create(vending_id: 1, drink_id: 36, temp: -1, value: 100);
VeRelationShip.create(vending_id: 1, drink_id: 60, temp: -1, value: 100);
VeRelationShip.create(vending_id: 1, drink_id: 37, temp: -1, value: 100);
VeRelationShip.create(vending_id: 2, drink_id: 14, temp: -1, value: 120);
VeRelationShip.create(vending_id: 2, drink_id: 122, temp: -1, value: 110);
VeRelationShip.create(vending_id: 2, drink_id: 84, temp: -1, value: 110);
VeRelationShip.create(vending_id: 2, drink_id: 50, temp: -1, value: 100);
VeRelationShip.create(vending_id: 2, drink_id: 102, temp: -1, value: 110);
VeRelationShip.create(vending_id: 2, drink_id: 91, temp: -1, value: 100);
VeRelationShip.create(vending_id: 2, drink_id: 123, temp: -1, value: 110);
VeRelationShip.create(vending_id: 2, drink_id: 124, temp: -1, value: 210);
VeRelationShip.create(vending_id: 2, drink_id: 150, temp: 1, value: 110);
VeRelationShip.create(vending_id: 2, drink_id: 14, temp: 1, value: 110);
VeRelationShip.create(vending_id: 2, drink_id: 22, temp: 1, value: 120);
VeRelationShip.create(vending_id: 2, drink_id: 23, temp: 1, value: 130);
VeRelationShip.create(vending_id: 2, drink_id: 26, temp: 1, value: 100);
VeRelationShip.create(vending_id: 2, drink_id: 153, temp: 1, value: 110);
VeRelationShip.create(vending_id: 2, drink_id: 61, temp: 1, value: 120);
VeRelationShip.create(vending_id: 2, drink_id: 62, temp: 1, value: 110);
VeRelationShip.create(vending_id: 2, drink_id: 53, temp: 1, value: 120);
VeRelationShip.create(vending_id: 2, drink_id: 55, temp: 1, value: 120);
VeRelationShip.create(vending_id: 2, drink_id: 56, temp: 1, value: 110);
VeRelationShip.create(vending_id: 2, drink_id: 57, temp: 1, value: 100);

